<a href="https://colab.research.google.com/github/sergiyenkoalina/machine-learning-course/blob/main/HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [2]:
import numpy as np

In [11]:
vector = np.random.rand(10)
print("\nВектор vector:")
print(vector)
print("\nРозмір вектора:")
print(vector.shape)


Вектор vector:
[0.76901703 0.44390624 0.88682466 0.52384919 0.06256938 0.39887522
 0.88734552 0.08976181 0.40171558 0.06971514]

Розмір вектора:
(10,)


In [9]:
matrix = np.array([[11, 14, 17],
                  [20, 23, 26],
                 [29, 32, 35],])
print("\Матриця matrix:")
print(matrix)
print("\nРозмір матриці:")
print(matrix.shape)

\Матриця matrix:
[[11 14 17]
 [20 23 26]
 [29 32 35]]

Розмір матриці:
(3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [12]:
vector+=10
vector = np.round(vector, 2)
print(vector)

[10.77 10.44 10.89 10.52 10.06 10.4  10.89 10.09 10.4  10.07]


In [13]:
matrix*=2
matrix

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [15]:
vector_quad = vector**2
vector_quad

array([115.9929, 108.9936, 118.5921, 110.6704, 101.2036, 108.16  ,
       118.5921, 101.8081, 108.16  , 101.4049])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [16]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [24]:
#1
result_matrix=np.dot(B,A)
print(result_matrix)

[[0.7281 0.5202]
 [0.2034 0.2846]]


In [25]:
#2
result_matrix_2 = np.dot(result_matrix, C)
print(result_matrix_2)

[[0.5202]
 [0.2846]]


In [26]:
#3
result_matrix_3 = np.dot(result_matrix, D)
print(result_matrix_3)

[[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [27]:
#1
result_matrix.T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [30]:
#2
print(vector.T)

[10.77 10.44 10.89 10.52 10.06 10.4  10.89 10.09 10.4  10.07]


**Спостереження**: немає зміни при транспонуванні, бо це одновимірний масив

In [31]:
#3
column_vector = np.expand_dims(vector, axis=1)
print(column_vector)

[[10.77]
 [10.44]
 [10.89]
 [10.52]
 [10.06]
 [10.4 ]
 [10.89]
 [10.09]
 [10.4 ]
 [10.07]]


**Спостереження**: тепер це стовпець

In [35]:
#3
print("\column_vector транспонований:")
print(column_vector.T)
print("\nРозмір column_vector.T:")
print(column_vector.T.shape)

\column_vector транспонований:
[[10.77 10.44 10.89 10.52 10.06 10.4  10.89 10.09 10.4  10.07]]

Розмір column_vector.T:
(1, 10)
